"""
Experiment 009: Per-sequence dirichlet gradient.

Each 200bp sequence is generated by smoothly interpolating between two
endpoint dirichlet compositions p_start, p_end ~ Dirichlet(0.5). At
position k, the composition is p_k = (1-t)*p_start + t*p_end with
t = k/199. Each base is iid sampled from p_k.

Unlike Markov-dirichlet (exp 003) which created long runs, gradients
keep diversity smooth and don't trigger homopolymers. This adds
within-sequence k-mer diversity on top of between-sequence composition
diversity (the dirichlet(0.5) baseline).

Hypothesis: if the model uses k-mer features beyond mononucleotide
composition, per-position composition variation should help. If only
overall composition matters, this will be a wash.
"""
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent / "sequences_0.txt"
SEED = 42
N = 50_000
LEN = 200
BASES = np.array(list("ACGT"))


def main():
    rng = np.random.default_rng(SEED)
    p_start = rng.dirichlet((0.5, 0.5, 0.5, 0.5), size=N)  # (N, 4)
    p_end = rng.dirichlet((0.5, 0.5, 0.5, 0.5), size=N)    # (N, 4)
    t = np.linspace(0, 1, LEN).reshape(1, LEN, 1)          # (1, L, 1)

    seqs = []
    for i in range(N):
        # Compositions per position: (LEN, 4)
        p_pos = (1 - t[0]) * p_start[i] + t[0] * p_end[i]
        # Sample one base per position using cumulative-CDF trick
        u = rng.random(LEN)
        cdf = np.cumsum(p_pos, axis=1)
        s = (u[:, None] < cdf).argmax(axis=1)
        seqs.append("".join(BASES[s]))

    OUT.write_text("\n".join(seqs) + "\n")
    print(f"wrote {N} gradient-dirichlet seqs to {OUT}")


if __name__ == "__main__":
    main()
